### ISSUE TITLE
Review dependabot PR to upgrade Flask

### ISSUE THREAD

**Issue by hectcastro** [azavea/docker-flask#10]
Dependabot opened https://github.com/azavea/docker-flask/pull/9 to upgrade Flask. Instead of merging the PR, sort out how to reconcile the change it wants to make with the current state of the repository.

**Comment by coalkettler** [comment]
@hectcastro The fix for [CVE-2019-1010083](https://nvd.nist.gov/vuln/detail/CVE-2019-1010083#vulnCurrentDescriptionTitle) hasn't been backported to versions prior to 1.0. #9 would effectively have us drop support for 0.12. 0.11 is reported as vulnerable as well.

Is that something we're willing to do? If not, I think our only option is to acknowledge the vulnerability and close the PR. I don't think we can reconcile this without upgrading to 1.0.

**Comment by hectcastro** [comment]
My suggestion would be to:

- Drop 0.11 and 0.12 from the build matrix (old tags published to Quay will remain, so that apps still depending on those container images won't break)
- Bump the version of 1.0.x
- Add 1.1.x to the build matrix
